### ISSUE TITLE
Previous Ranks and MMR don’t appear?

### ISSUE THREAD

**Issue by Krjen** [r6db/r6db#25]
I went to go look up my stats to show a friend and it only shows I was Platinym 1 in Season 6. It does not show my previous ranks that I have gotten. I was Platinum 1 Season 3 (Around 4950Mmr ) Platinum 3 season 4 (Around 3100Mmr), and Platinum 3 Season 5 (Around 3330Mmr). Any ideas if or when you’re gonna give me back the stats so I can brag to my friends that They are only golds. Kappa. Thanks if you fix it for everyone or just add the stats to my profile directly. My Xbox Gamertag is ToxicBombs64.

**Comment by NaughtyMuppet** [comment]
Coinciding with us getting hacked ubisoft broke their API. 
Once this page -> https://game-rainbow6.ubi.com/en-gb/uplay/rewards/season/4
is fixed we can refetch the old seasons

**Comment by NaughtyMuppet** [comment]
Still no update on that front...

**Comment by NaughtyMuppet** [comment]
Small update, looks like they're at least trying to fix it https://www.reddit.com/r/Rainbow6/comments/7amx8b/comment/dpf4rdy

**Comment by LaxisB** [comment]
still broken: https://twitter.com/UbisoftSupport/status/945759496906985477
"will look into it"

**Comment by LaxisB** [comment]
i'll close this, as i don't believe that this data will ever come back
